### PR TITLE
Reproducible example plot for MATLAB and Python, refactoring

### PR DESCRIPTION
**Pull request by eejd**
a minor name change and refactoring of the matlab code
added runable examples

### CODE REVIEW

**Comment by glopesdev** [comment]
Why do you feel it's necessary to change the frame "second" to "clock_second"?

My argument for it being called "second" is that it follows the official protocol specification from Filipe. This makes it easier to match the frame structure elements to the protocol specification and avoids proliferation of names.

I would keep it "second" unless there is some unsurmountable reason. If such a reason exists, then we should discuss it with Filipe as well as I would not want the naming conventions between the parser and the protocol to differ.

**Comment by eejd** [comment]
I will revert to "second", but I think that we might want to discuss with Filipe. The reason is only that from the user perspective, many samples will have the same second (integer) but actually will be from different times within the second (i.e. sampling milliseconds). But I think perhaps it shouldn't be done here and I'm reverting.

**Comment by eejd** [comment]
Ok, the code compiles and I also forced frequency specification (for now) in both matlab and python. Otherwise, it's easy to cause failures with the wrong default frequency. You should be able to pull.

**Comment by glopesdev** [comment]
Great!
I agree it makes sense that frequency should be mandatory.

**Pull request merged**
